# Generated by Django 5.0.6 on 2024-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskeymanager',
            options={'ordering': ['-procurement_date'], 'verbose_name_plural': 'Access Key Manager'},
        ),
        migrations.AddField(
            model_name='accesskeymanager',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accesskeymanager',
            name='expiry_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='accesskeymanager',
            name='procurement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
