# Generated by Django 5.0.6 on 2024-06-18 00:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymanager',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
