# Generated by Django 5.0.6 on 2024-07-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0003_rename_accesskeymanager_accesskey_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskey',
            options={'ordering': ['-procurement_date'], 'verbose_name_plural': 'Access Key'},
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='procurement_date',
            field=models.DateTimeField(default=None),
        ),
    ]
